/*
* Automatically generated by 'ng g ng-alain:plugin icon'
* @see https://ng-alain.com/cli/plugin#icon
*/

import {
  AppstoreOutline,
  CopyrightOutline,
  DashboardOutline,
  FilterOutline,
  GlobalOutline,
  LockOutline,
  LogoutOutline,
  MailOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  MessageOutline,
  PieChartOutline,
  RollbackOutline,
  SettingOutline,
  UserOutline,
  WarningOutline
} from '@ant-design/icons-angular/icons';

export const ICONS_AUTO = [
  AppstoreOutline,
  CopyrightOutline,
  DashboardOutline,
  FilterOutline,
  GlobalOutline,
  LockOutline,
  LogoutOutline,
  MailOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  MessageOutline,
  PieChartOutline,
  RollbackOutline,
  SettingOutline,
  UserOutline,
  WarningOutline
];
