export const USER_PERMISSION = {
  READER_USER_PROFILE_READ: 'E151',
  READER_USER_REQUEST_CREATE: 'E152',
  PACKAGE_READ: 'E921',

  CONTACT_CONTRACT_APPROVE: '1EA07',
  CONTACT_CONTRACT_CREATE: '1EA02',
  CONTACT_CONTRACT_DELETE: '1EA04',
  CONTACT_CONTRACT_DOWNLOAD: '1EA05',
  CONTACT_CONTRACT_READ: '1EA01',
  CONTACT_CONTRACT_UPDATE: '1EA03',

  CUSTOMER_CUSTOMER_CREATE: '1E802',
  CUSTOMER_CUSTOMER_DELETE: '1E804',
  CUSTOMER_CUSTOMER_READ: '1E801',
  CUSTOMER_CUSTOMER_UPDATE: '1E803',

  OPPORTUNITY_OPPORTUNITY_CREATE: '1E902',
  OPPORTUNITY_OPPORTUNITY_DELETE: '1E904',
  OPPORTUNITY_OPPORTUNITY_READ: '1E901',
  OPPORTUNITY_OPPORTUNITY_UPDATE: '1E903',

  OPPORTUNITY_OPPORTUNITYPROCESS_CREATE: '1E912',
  OPPORTUNITY_OPPORTUNITYPROCESS_DELETE: '1E914',
  OPPORTUNITY_OPPORTUNITYPROCESS_READ: '1E911',
  OPPORTUNITY_OPPORTUNITYPROCESS_UPDATE: '1E913',

  OPPORTUNITY_PRICEQUOTE_APPROVE: '1E967',
  OPPORTUNITY_PRICEQUOTE_CLOSE: '1E966',
  OPPORTUNITY_PRICEQUOTE_CREATE: '1E962',
  OPPORTUNITY_PRICEQUOTE_DELETE: '1E964',
  OPPORTUNITY_PRICEQUOTE_READ: '1E961',
  OPPORTUNITY_PRICEQUOTE_UPDATE: '1E963',

  OPPORTUNITY_SURVEYRECORDS_CREATE: '1E952',
  OPPORTUNITY_SURVEYRECORDS_DELETE: '1E954',
  OPPORTUNITY_SURVEYRECORDS_READ: '1E951',
  OPPORTUNITY_SURVEYRECORDS_UPDATE: '1E953',

  RES_BUSINESSTYPE_CREATE: '1E432',
  RES_BUSINESSTYPE_DELETE: '1E434',
  RES_BUSINESSTYPE_READ: '1E431',
  RES_BUSINESSTYPE_UPDATE: '1E433',

  RES_CONTRACTTYPE_CREATE: '1E462',
  RES_CONTRACTTYPE_DELETE: '1E464',
  RES_CONTRACTTYPE_READ: '1E461',
  RES_CONTRACTTYPE_UPDATE: '1E463',

  RES_CUSTOMERGROUP_CREATE: '1E422',
  RES_CUSTOMERGROUP_DELETE: '1E424',
  RES_CUSTOMERGROUP_READ: '1E421',
  RES_CUSTOMERGROUP_UPDATE: '1E423',

  RES_MARKETTINGSOURE_CREATE: '1E452',
  RES_MARKETTINGSOURE_DELETE: '1E454',
  RES_MARKETTINGSOURE_READ: '1E451',
  RES_MARKETTINGSOURE_UPDATE: '1E453',

  PIM_ADMIN: 'E700',

  PIM_PRODUCT_CREATE: 'E712',
  PIM_PRODUCT_DELETE: 'E714',
  PIM_PRODUCT_READ: 'E711',
  PIM_PRODUCT_UPDATE: 'E713',

  PIM_PRODUCTCATEGORY_CREATE: 'E742',
  PIM_PRODUCTCATEGORY_DELETE: 'E744',
  PIM_PRODUCTCATEGORY_READ: 'E741',
  PIM_PRODUCTCATEGORY_UPDATE: 'E743'
};
